Repository qtranslate/qtranslate-xt, pull requests merged in 2023-04, with the labels that each got.

#1307 Bump ACF minimal version 5.6.0
  src/modules/acf/admin.php
  src/modules/acf/extended.php
  src/modules/acf/fields/file.php
  src/modules/acf/fields/image.php
  src/modules/acf/fields/post_object.php
  src/modules/acf/fields/text.php
  src/modules/acf/fields/textarea.php
  src/modules/acf/fields/url.php
  src/modules/acf/fields/wysiwyg.php
  src/modules/acf/loader.php
Labels: module: ACF

#1311 Moved deprecated functions to a separate file.
  src/admin/admin.php
  src/admin/admin_options.php
  src/admin/admin_options_update.php
  src/admin/admin_utils.php
  src/admin/update_gettext_db.php
  src/date_time.php
  src/deprecated.php
  src/init.php
  src/language_blocks.php
  src/options.php
Labels: core

#1316 Lint PHP by removing unnecessary local vars
  src/admin/admin.php
  src/admin/admin_options_update.php
  src/admin/admin_settings.php
  src/admin/admin_taxonomy.php
  src/admin/admin_utils_db.php
  src/admin/block_editor.php
  src/date_time.php
  src/frontend.php
  src/language_blocks.php
  src/modules/gravity-forms/loader.php
  src/url.php
Labels: core

#1317 Lint PHP by simplifying expressions
  src/admin/activation_hook.php
  src/admin/admin.php
  src/admin/admin_options_update.php
  src/admin/admin_settings.php
  src/admin/admin_settings_language_list.php
  src/admin/admin_utils_db.php
  src/admin/block_editor.php
  src/date_time.php
  src/frontend.php
  src/language_blocks.php
  src/modules/slugs/admin_migrate_qts.php
  src/options.php
  src/taxonomy.php
  src/url.php
Labels: core

#1321 Delete admin translator, tidy up front interface
  src/admin/admin.php
  src/admin/admin_class_translator.php
  src/admin/i18n-interface-admin.php
  src/class_translator.php
  src/init.php
  src/translator_interface.php
Labels: core

#1322 Rename `i18n_content_translation_not_available` filter
  src/language_blocks.php
Labels: core

#1323 Rename `QTX_Translator::translate_{item}` filters
  dev/qtx-tests.php
  src/class_translator.php
  src/translator_interface.php
Labels: core

#1324 Fix custom URL for admin area and login page
  src/language_detect.php
  src/modules/slugs/slugs.php
  src/url.php
Labels: enhancement, core
